### ISSUE TITLE
Stop it

### ISSUE THREAD

**Issue by Skayo** [Parou/Mini-Steak-with-Eggplant-Peach-Balsamic-Sauce-and-Pak-Choi#1]
Get some help

**Comment by Skayo** [comment]
Stop posting recipes on GitHub

**Comment by Skayo** [comment]
pls

**Comment by PerhapsSomeone** [comment]
no

**Comment by PerhapsSomeone** [comment]
recipes good

**Comment by Parou** [comment]
I can't people are requesting it! I need to support my fans!

**Comment by Skayo** [comment]
Microsoft only buys GitHub to own your recipes! They will use them and make money with them!
As I said above: YOU NEED TO STOP!

It's for your own safety!

**Comment by Skayo** [comment]
Please listen!

**Comment by cozyplanes** [comment]
no

**Comment by Haxk20** [comment]
Recipes are good. Her recipes are very tasty.

**Comment by lennart-k** [comment]
Wtf, never ever stop these amazing recipes!
I'd say this issue should be immediately closed!

**Comment by Skayo** [comment]
That's rude

**Comment by Skayo** [comment]
I'll close this now

**Comment by PerhapsSomeone** [comment]
no >:(
